### ISSUE TITLE
有一点不太明白

### ISSUE THREAD

**Issue by lijianfeigeek** [kenberkeley/vue-state-management-alternative#1]
click 事件是如何进入到 mixins 里的 methods 调用的，感谢!

**Comment by kenberkeley** [comment]
这就是 Vue - mixin 的用法

**Comment by lijianfeigeek** [comment]
这个调用是如何进入到 mixins  里面的呢？

**Comment by lijianfeigeek** [comment]
例如 App.vue  里的 click 方法 resetTodos 不是应该去script 对应的 methods 里的方法吗？data下面没有methods，却找到里 mixins 的methods 。不太明白这个调用过程。感谢回答！

**Comment by kenberkeley** [comment]
抱歉，刚去吃饭了。建议你先看看 Vue 的官方文档有关 mixin 方面的内容

**Comment by lijianfeigeek** [comment]
感谢指点，看懂了！谢谢！
